version: '3.8'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-nextcloud:
    image: nextcloud:14.0
    container_name:  §§INSTANCE-nextcloud
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=§§MARIADB_PASSWORD
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=v
      - NEXTCLOUD_ADMIN_PASSWORD=vendetta
    links:
      - §§INSTANCE-nextcloud-db:nextcloud-db
    ports:
      - "80"
    depends_on:
      - §§INSTANCE-nextcloud-db
    volumes: 
      - ./data/html:/var/www/html
      - ./config:/var/www/html/config
      - ./entrypoint.sh:/var/entrypoint.sh
    environment:
      - INSTANCENAME=§§INSTANCE
      - BASE_PATH="/§§INSTANCE"
      - TARGET="/var/www/html/§§INSTANCE"
    entrypoint: /var/entrypoint.sh

  §§INSTANCE-nextcloud-db:
    image: mariadb
    container_name: §§INSTANCE-nextcloud-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=§§MARIADB_ROOT_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=§§MARIADB_PASSWORD
      - NEXTCLOUD_ADMIN_USER=v
      - NEXTCLOUD_ADMIN_PASSWORD=vendetta
    volumes:
      - ./data/mysql:/var/lib/mysql
