version: '2'

services:

  bibbox-nextcloud:
    image: nextcloud:14.0
    container_name:  bibbox-nextcloud
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=bibboxlocal
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=v
      - NEXTCLOUD_ADMIN_PASSWORD=vendetta
    links:
      - bibbox-nextcloud-db:nextcloud-db
    ports:
      - "8065:80"
    depends_on:
      - bibbox-nextcloud-db
      - bibbox-nextcloud-data
    volumes_from: 
      - bibbox-nextcloud-data

  bibbox-nextcloud-db:
    image: mariadb
    container_name: bibbox-nextcloud-db
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=bibboxlocal
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=bibboxlocal
    volumes_from:
      - bibbox-nextcloud-data
    depends_on:
      - bibbox-nextcloud-data

  bibbox-nextcloud-data:
    image: busybox
    container_name: bibbox-nextcloud-data
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/data:/var/www/html/data
      - ./data/apps:/var/www/html/apps

